name: build, test and deploy application

on: 
  pull_request:
    branches: [ main ]

# job that runs tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
           node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Test
        run: npm run test

  # job that merges if tests pass and no conflicts detected
  # merge:
  #   runs-on: ubuntu-latest
  #   needs: [ test ]
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Merge      
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         merge_method: squash
  #         commit_message: "Merged PR ${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
  #         delete_branch: true

  # job that builds and deploys to azure
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    needs: [ test ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
           node-version: '16'
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_ROCK_047663903 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_ROCK_047663903 }}      





        