#check if we are on a feature branch
#run our tests
#if tests pass we want to create a pull request to merge our feature branch into main
#check if the commit massage has the word "ready" in it

name:  Feature Ready

on: 
   push: 
     branches: 
       -  feature/**

jobs:

    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js 16.x
          uses: actions/setup-node@v1
          with:
            node-version: '16'
        - name: Install dependencies
          run: npm install
        - name: Test
          run: npm run test

    feature_ready:
      runs-on: ubuntu-latest
      needs: [ test ]
      steps:
        - uses: actions/checkout@v2
        - name:  Check if commit message has "ready"
          id :  check_commit_message
          run :  |
            if [[ ${{ github.event.head_commit.message }} == *"ready"* ]]; then
              echo "::set-output name=ready::true"
            else
              echo "::set-output name=ready::false"
            fi
        - name:  Create Pull Request
          if:  steps.check_commit_message.outputs.ready == 'true'
          uses:  peter-evans/create-pull-request@v3
          with:
            token:  ${{ secrets.GITHUB_TOKEN }}
            commit-message:  "Merged PR ${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
            title:  "Merged PR ${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
            body:  "Merged PR ${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
            branch:  main
            base:  main
            delete-branch:  false
            labels:  ready
